### PR TITLE
Fixes Windows compatibility issue

### LINKED ISSUE #49: Fix Windows compatibility issue
Resolve bug with running server on Windows machines

```> hire-wire@1.0.0 start
> node server.js

node:internal/modules/esm/load:249
    throw new ERR_UNSUPPORTED_ESM_URL_SCHEME(parsed, schemes);
          ^

Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/load:249:11)
    at defaultLoad (node:internal/modules/esm/load:130:3)
    at ModuleLoader.load (node:internal/modules/esm/loader:555:13)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:434:56)
    at new ModuleJob (node:internal/modules/esm/module_job:71:27)
    at #createModuleJob (node:internal/modules/esm/loader:447:17)
    at ModuleLoader.getJobFromResolveResult (node:internal/modules/esm/loader:259:34)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:17)
    at async ModuleLoader.import (node:internal/modules/esm/loader:472:23) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}```

### PR DESCRIPTION
**Pull request by stevenhcau**
Concerns:
- Test on Mac/Unix system to ensure cross-platform compatibility

**What does this PR do?**

- Fixed compatibility issues with Windows machines not being able to start the server in `\models\index.js`
- Resolved connection issues by adding a try-catch in `tests\models\user.test.js`
- Resolved jest module incompatibility by making modification in `package.json`

**List of task completed**

-   Fixes compatibility issues with Windows machines not being able to run the server
-  Fixes jest testing suite causing errors on Windows machines

**How can this be tested?**

- `npm start` and `npm test` should be successful

**Additional info**

Add more info if any. eg fixes #.

### CODE REVIEW

File: src/models/index.js [hunk 1]
```diff
@@ -1,33 +1,40 @@
 import fs from 'fs';
 import path from 'path';
-import { fileURLToPath } from 'url';
+import { fileURLToPath, pathToFileURL } from 'url';
 import { Sequelize } from 'sequelize';
 import configFile from '../config/config.js';
 
-const basename = path.basename(fileURLToPath(import.meta.url));
+console.log(import.meta.url);
```
Comment (OreLana) [inline src/models/index.js]: Hey Steven, can we remove this console.log statement here.

**Review by OreLana — APPROVED** [review]
Looks good!
